#=======================================================================================
# Global Config
#=======================================================================================
spring:
  application:
    name: worker
  profiles:
    active: "dev"
  security:
    user:
      name: user
      password: testpassword

---
#=======================================================================================
# Development Profile Config
#=======================================================================================
spring:
  profiles: dev
server:
  port: 8081


---
#=======================================================================================
# Production ProfileConfig - ALL CONFIG SHOULD BE PASSED AS ENV VARIABLES
#=======================================================================================
spring:
  profiles: production
server:
  port: 8081